 // This is autogenerated content
    export const gzipData = [
  {
    "type": "gzip",
    "level": 1,
    "compressionTime": 21.900665998458862,
    "compressedByteLength": 1280848,
    "decompressionTime": 9.990125000476837,
    "decompressedByteLength": 13267693
  },
  {
    "type": "gzip",
    "level": 2,
    "compressionTime": 22.113499999046326,
    "compressedByteLength": 1234131,
    "decompressionTime": 8.597833037376404,
    "decompressedByteLength": 13267693
  },
  {
    "type": "gzip",
    "level": 3,
    "compressionTime": 23.47220802307129,
    "compressedByteLength": 1201919,
    "decompressionTime": 8.411125004291534,
    "decompressedByteLength": 13267693
  },
  {
    "type": "gzip",
    "level": 4,
    "compressionTime": 46.07233399152756,
    "compressedByteLength": 1102444,
    "decompressionTime": 8.14612501859665,
    "decompressedByteLength": 13267693
  },
  {
    "type": "gzip",
    "level": 5,
    "compressionTime": 49.13983404636383,
    "compressedByteLength": 1001802,
    "decompressionTime": 7.476042032241821,
    "decompressedByteLength": 13267693
  },
  {
    "type": "gzip",
    "level": 6,
    "compressionTime": 57.38254201412201,
    "compressedByteLength": 947206,
    "decompressionTime": 7.366041958332062,
    "decompressedByteLength": 13267693
  },
  {
    "type": "gzip",
    "level": 7,
    "compressionTime": 65.549624979496,
    "compressedByteLength": 930406,
    "decompressionTime": 7.199124991893768,
    "decompressedByteLength": 13267693
  },
  {
    "type": "gzip",
    "level": 8,
    "compressionTime": 105.62220901250839,
    "compressedByteLength": 905848,
    "decompressionTime": 6.959916949272156,
    "decompressedByteLength": 13267693
  },
  {
    "type": "gzip",
    "level": 9,
    "compressionTime": 114.3160839676857,
    "compressedByteLength": 905214,
    "decompressionTime": 6.629709005355835,
    "decompressedByteLength": 13267693
  }
]

    export const brData = [
  {
    "type": "br",
    "level": 1,
    "compressionTime": 7.80162501335144,
    "compressedByteLength": 617999,
    "decompressionTime": 7.95612496137619,
    "decompressedByteLength": 13267693
  },
  {
    "type": "br",
    "level": 2,
    "compressionTime": 16.004332959651947,
    "compressedByteLength": 515887,
    "decompressionTime": 6.691291987895966,
    "decompressedByteLength": 13267693
  },
  {
    "type": "br",
    "level": 3,
    "compressionTime": 18.468500018119812,
    "compressedByteLength": 493723,
    "decompressionTime": 6.554750025272369,
    "decompressedByteLength": 13267693
  },
  {
    "type": "br",
    "level": 4,
    "compressionTime": 22.620040953159332,
    "compressedByteLength": 463776,
    "decompressionTime": 6.070208013057709,
    "decompressedByteLength": 13267693
  },
  {
    "type": "br",
    "level": 5,
    "compressionTime": 46.65395903587341,
    "compressedByteLength": 424862,
    "decompressionTime": 7.259375035762787,
    "decompressedByteLength": 13267693
  },
  {
    "type": "br",
    "level": 6,
    "compressionTime": 51.87883299589157,
    "compressedByteLength": 420631,
    "decompressionTime": 7.130249977111816,
    "decompressedByteLength": 13267693
  },
  {
    "type": "br",
    "level": 7,
    "compressionTime": 70.66420900821686,
    "compressedByteLength": 417726,
    "decompressionTime": 7.1861249804496765,
    "decompressedByteLength": 13267693
  },
  {
    "type": "br",
    "level": 8,
    "compressionTime": 84.17141604423523,
    "compressedByteLength": 415027,
    "decompressionTime": 6.653166949748993,
    "decompressedByteLength": 13267693
  },
  {
    "type": "br",
    "level": 9,
    "compressionTime": 154.82595801353455,
    "compressedByteLength": 411890,
    "decompressionTime": 7.442209005355835,
    "decompressedByteLength": 13267693
  },
  {
    "type": "br",
    "level": 10,
    "compressionTime": 1919.052249968052,
    "compressedByteLength": 374965,
    "decompressionTime": 7.0309590101242065,
    "decompressedByteLength": 13267693
  },
  {
    "type": "br",
    "level": 11,
    "compressionTime": 5638.124957978725,
    "compressedByteLength": 357754,
    "decompressionTime": 6.4777079820632935,
    "decompressedByteLength": 13267693
  }
]

    